name: emotion-fan
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.0
  - cudnn=7.6.5
  - numpy=1.17.2
  - pillow=6.2.0
  - pip=20.0
  - python=3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
